### ISSUE TITLE
[Idea Not an issue!🌟]

### ISSUE THREAD

**Issue by GreekKennyS** [jay-jay0101/simplymore#4]
Can you make some weapons glow or act like a torch when you have the lambdynamiclights or any dynamiclights mod?
And maybe make it a toggle through the cloth config thats it its still a perfect mod it deserves more downloads it is very awesome the abilities the design and everything

**Comment by jay-jay0101** [comment]
Hey, thanks for the suggestion! The next time I update this mod for a bugfix, I'll try see if I can add this on.

**Comment by jay-jay0101** [comment]
I did try looking, but everything I could find about it was really confusing or outdated. I might try look at it for a later update, but for now I can't figure it out. I tried my best haha 😅

**Comment by jay-jay0101** [comment]
Added in an update dropping later today.
