### ISSUE TITLE
Compact issue

### ISSUE THREAD

**Issue by R4llik** [jay-jay0101/simplymore#6]
1.20.1

SimplyMore cant be reforged with use of mod called "Tierify" (by ElocinDev)

1. Go to anvil
2. Click on second tab
3. Place weapon in middle slot, weapon specific material (runic tablet in this case) in left slot, and reforging material ex. galena

SimplyMore weapons should normally reforge just like weapons from SimplySwords

**Comment by jay-jay0101** [comment]
I cannot replicate this issue.

![image](https://github.com/user-attachments/assets/4fcf4f1e-9712-4354-9178-8e1396d73284)
![image](https://github.com/user-attachments/assets/c74d0077-fe89-4274-afc8-d3296bf6d658)
