### ISSUE TITLE
[BUG] Mipmap issues with Simply More [Fabric 1.20.1/0.16.9]

### ISSUE THREAD

**Issue by pokesmells** [jay-jay0101/simplymore#7]
**Version**
1.20.1 Fabric/0.16.9 Mod Version - simplymore-1.0.2+1.20.1.jar

**Describe the bug**
Wrong texture sizes force the mipmap level down which make the game look awful.

**To Reproduce**
Just start the game and look at the logs and the game it self

**Screenshots**
![Screenshot 2024-11-14 074142](https://github.com/user-attachments/assets/c063d732-496c-45e9-ba41-f32f408a6660)

**Additional context**
Your mod due to it's mipmap issues forces the level to a whopping **Zero**

![image](https://github.com/user-attachments/assets/212214e4-69ef-4da0-90f3-97de3a56a50b)
Mipmap level 0

![image](https://github.com/user-attachments/assets/4da1a16e-0a1e-4aaf-9806-2d86044807fa)
Mipmap level 4

You can see the clear differences, please fix these issues as it makes the game look terrible, breaks the texture atlas and can easily be fixed by resizing.

**Comment by jay-jay0101** [comment]
I was aware of the inconsistent sizes, but I didn't realise it caused this! 

I will fix this in the next update.

**Comment by jay-jay0101** [comment]
Fixed! An update will be dropping later tonight that fixes this issue.
