### ISSUE TITLE
Items are not tagged correctly

### ISSUE THREAD

**Issue by naomieow** [jay-jay0101/simplymore#8]
**Version**
Minecraft: 1.20.1
Fabric: 0.16.9
Simply More: 1.0.3
Simply Swords - 1.56.0

**Describe the bug**
Simply More weapons are not included in the `#c:swords` or `#c:weapons` item tags.

**To Reproduce**
1. Add a `minecraft:iron_sword`, a `simplyswords:iron_longsword` and a `simplymore:iron_dagger` to your inventory
2. Enter the command `/clear @s #c:swords`
3. Only the `minecraft:iron_sword` and `simplyswords:iron_longsword` are removed.

**Expected behavior**
All items are removed.

**Screenshots**
![image](https://github.com/user-attachments/assets/012b9cb6-4056-45e1-95e6-5dec40dd4c3b)
![image](https://github.com/user-attachments/assets/0422d213-fa6d-47ae-8351-ae26ba4355cb)

**Comment by jay-jay0101** [comment]
I have an update coming later next week, I will try to remember to fix this, thanks.

**Comment by jay-jay0101** [comment]
Is there any other c-tags that the weapons should be added to other than the two you've sent?

**Comment by naomieow** [comment]
There is also `#c:spears`. I encountered this while working on another mod, so not entirely familiar with the *rest* of the tags.

**Comment by jay-jay0101** [comment]
Fixed in V1.1.0, dropping sometime this week.
